name: CI

on:
  workflow_dispatch:
    inputs:
      target_arch:
        description: '目标架构'
        required: false
        default: 'all'
        type: choice
        options:
          - all
          - linux
          - windows
          - macos
          - android-arm64
      build_type:
        description: '构建类型'
        required: false
        default: 'release'
        type: choice
        options:
          - release
          - debug
  push:
    branches:
      - main

jobs:
  build-java:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: recursive
      - uses: actions/setup-java@v5
        with:
          distribution: liberica
          java-version: 17
      - uses: gradle/actions/setup-gradle@v6
      - run: ./gradlew build

  build-natives:
    needs: build-java
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        type: [android-arm64]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install Android dependencies
        run: |
          sudo apt update
          sudo apt install -y unzip wget ninja-build pkg-config
          wget https://dl.google.com/android/repository/android-ndk-r27c-linux.zip
          unzip -q android-ndk-r27c-linux.zip
          echo "ANDROID_NDK_HOME=$(pwd)/android-ndk-r27c" >> $GITHUB_ENV
          echo "$(pwd)/android-ndk-r27c/toolchains/llvm/prebuilt/linux-x86_64/bin" >> $GITHUB_PATH
      - name: Build Native
        run: |
          chmod +x buildSrc/scripts/build.sh
          ./buildSrc/scripts/build.sh android-arm64 release
      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: native-library-android-arm64
          path: /tmp/imgui/dst/
